## Advent of code 2020 - day 1 - [Report Repair](https://adventofcode.com/2020/day/1)
### numpy and pandas solutions

In [1]:
import numpy as np
import pandas as pd

##### numpy solution for given example part one.

In [2]:
t0 = np.array([1721, 979, 366, 299, 675, 1456])
t0

array([1721,  979,  366,  299,  675, 1456])

In [3]:
t0_sums = t0.reshape(len(t0), 1) + t0.reshape(1, len(t0))
t0_sums

array([[3442, 2700, 2087, 2020, 2396, 3177],
       [2700, 1958, 1345, 1278, 1654, 2435],
       [2087, 1345,  732,  665, 1041, 1822],
       [2020, 1278,  665,  598,  974, 1755],
       [2396, 1654, 1041,  974, 1350, 2131],
       [3177, 2435, 1822, 1755, 2131, 2912]])

In [4]:
t0_index = np.where(t0_sums == 2020)
t0_index

(array([0, 3]), array([3, 0]))

In [5]:
t0_values = t0[t0_index[0]]
t0_values

array([1721,  299])

In [6]:
t0_answer = np.prod(t0_values)
t0_answer

514579

##### numpy solution part one.

In [7]:
day1 = np.loadtxt('2020_1.txt')
day1_sums = day1.reshape(len(day1), 1) + day1.reshape(1, len(day1))
day1_index = np.where(day1_sums == 2020)
day1_values = day1[day1_index[0]]
day1_answer = np.prod(day1_values)
print('solution part one:', int(day1_answer))

solution part one: 703131


##### pandas solution for given example part one.

In [8]:
t1 = pd.DataFrame([1721, 979, 366, 299, 675, 1456], columns=['expenses'])
t1['diff_2020'] = 2020 - t1['expenses']
t1['present'] = t1['diff_2020'].isin(t1['expenses'])
t1['product'] = t1['expenses'] * t1['diff_2020'] * t1['present']
t1

expenses  diff_2020  present  product
0      1721        299     True   514579
1       979       1041    False        0
2       366       1654    False        0
3       299       1721     True   514579
4       675       1345    False        0
5      1456        564    False        0

In [9]:
t1['product'].max()

514579

##### pandas solution part one.

In [10]:
day1b = pd.read_csv('2020_1.txt', header=None, names=['expenses'])
day1b['diff_2020'] = 2020 - day1b.expenses
day1b['present'] = day1b.diff_2020.isin(day1b.expenses)
day1b['product'] = day1b.expenses * day1b.diff_2020 * day1b.present
day1b[day1b.present == True]

expenses  diff_2020  present  product
94        447       1573     True   703131
106      1573        447     True   703131

In [11]:
day1b_answer = day1b['product'].max()
print('solution part one:', int(day1b_answer))

solution part one: 703131
